version: '3'

services:
  
  market_back:
    container_name: market_back
    build: MarketApi 
    env_file:
      - .env
    environment:
      ASPNETCORE_URLS : 'http://0.0.0.0:5000'
    depends_on:
      - database
    ports:
      - 3101:5000
  
  market_identety:
    container_name: market_identety
    build: Identety 
    env_file:
      - .env
    environment:
      ASPNETCORE_URLS : 'http://0.0.0.0:5001'
      database : 'Identety'
    depends_on:
      - database
    ports:
      - 3102:5001
      
  market_front:
    container_name: market_front
    build: ClientApp
    volumes:
      -  ./assets:/usr/share/nginx/html/assets
      -  ./assets:/etc/nginx/assets
      -  ./assets:/usr/share/nginx/assets
    depends_on:
      - market_back
    links:
      - market_back
    ports:
      - "82:81"
    environment:
      - NGINX_PORT=81
      
  market_admin_app:
    container_name: market_admin_app
    build: Market.AdminApp
    volumes:
      -  ./assets:/usr/share/nginx/html/assets
      -  ./assets:/etc/nginx/assets
      -  ./assets:/usr/share/nginx/assets
    depends_on:
      - market_back
    links:
      - market_back
    ports:
      - "83:82"
    environment:
      - NGINX_PORT=82
  
      
      
  database:
    image: postgres:14
    container_name: database
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD : '1'
      POSTGRES_USER : 'postgres'
    ports:
      - 5433:5432    	
  
  
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_PORT=80
    depends_on:
      - market_back
      - market_identety
      - market_front
      - market_admin_app      
    links:
      - market_back
      - market_identety       
      - market_front
      - market_admin_app
  
 
